# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default
 
steps:

- script: sudo apt update
  displayName: 'update a repo'

- script: sudo apt install tree maven zip docker.io openjdk-8-jdk -y 
  displayName: 'install dependency'

- script: sudo mvn clean
  displayName: 'perform maven clean'
  
- script: sudo mvn compile
  displayName: 'perform maven compile'
  
- script: sudo mvn sonar:sonar -Dsonar.projectKey=cloudenabled -Dsonar.host.url=http://172.20.105.57:9000 -Dsonar.login=9f7360036cea0c7fd1eeb319b9136f1001c3c1b3
  displayName: 'perform sonar analysis'
  
- script: sudo mvn test
  displayName: 'perform maven tests'

- script: sudo mvn surefire-report:report
  displayName: 'generate reports'
  
- script: sudo zip -r site-anil.zip target/site/*
  displayName: 'zip all unit test reports'

- script: curl -v -u admin:CloudEnabled --upload-file site-anil.zip http://172.20.105.62:8081/repository/maven-releases/
  displayName: 'upload unit test report to nexus'
  
- script: sudo mvn package
  displayName: 'perform maven package'

- script: curl -v -u admin:CloudEnabled --upload-file target/todorest-0.0.1-SNAPSHOT.jar http://172.20.105.62:8081/repository/maven-releases/
  displayName: 'upload jar nexus'

- script: sudo docker build -t anilbidari/todo:12.0 .
  displayName: 'build docker image'

- script: sudo docker login -u $(dockerid) -p $(dockerhub-pwd)
  displayName: 'docker login'


- script: sudo docker push anilbidari/todo:12.0
  displayName: 'docker upload image'

- script: sudo docker run -itd -p 8080 anilbidari/todo:12.0 /bin/bash
  displayName: 'run container'

- script: sudo docker ps -l
  displayName: 'list container'

